{{- if and (include "agent-platform.ingress.agentgateway" .) .Values.gateway.parameters.enabled }}
{{- $env := concat (include "agent-platform.otlpEnv" . | fromYamlArray) (.Values.gateway.parameters.dataPlaneEnv | default list) }}
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: {{ include "agent-platform.parametersName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-platform-standalone.labels.common" . | nindent 4 }}
spec:
  {{- with .Values.agentgateway.agentgateway.proxy.image }}
  image:
    registry: {{ .registry }}
    repository: {{ .repository }}
    {{- with .tag }}
    tag: {{ . }}
    {{- end }}
  {{- end }}
  service:
    {{- if (include "agent-platform.edgeIsDataPlane" .) }}
    type: {{ .Values.gatewayApi.gateway.serviceType }}
    {{- else }}
    type: {{ .Values.gateway.parameters.serviceType }}
    {{- end }}
  deployment:
    spec:
      template:
        spec:
          automountServiceAccountToken: true
          securityContext:
            {{- toYaml .Values.gateway.parameters.podSecurityContext | nindent 12 }}
          {{- with .Values.gateway.parameters.dataPlaneVolumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: agentgateway
              securityContext:
                {{- toYaml .Values.gateway.parameters.containerSecurityContext | nindent 16 }}
              {{- with .Values.gateway.parameters.dataPlaneResources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.gateway.parameters.dataPlaneVolumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
{{- end }}
