package main

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// BuildChartYAML emits Chart.yaml: the static metadata from the config plus
// one dependency per configured entry with an exact, resolved version.
func BuildChartYAML(config *Config, components []FleetComponent, resolved map[string]string) (*yaml.Node, error) {
	chart := newMapping()
	chart.Content = append(chart.Content, config.Chart.Content...)

	dependencies := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, dependency := range config.Dependencies {
		version, ok := resolved[dependency.Name]
		if !ok {
			return nil, fmt.Errorf("no resolved version for %q", dependency.Name)
		}
		if err := checkMajor(dependency, version); err != nil {
			return nil, err
		}
		repository := dependency.Repository
		if !dependency.IsExtra() {
			component, ok := fleetComponentByChart(components, dependency.Name)
			if !ok {
				return nil, fmt.Errorf("dependency %q is not a fleet component", dependency.Name)
			}
			repository = component.Repository
		}
		entry := newMapping()
		mappingSet(entry, newScalar("name"), newScalar(dependency.Name))
		versionNode := newScalar(version)
		versionNode.Style = yaml.DoubleQuotedStyle
		versionNode.LineComment = fmt.Sprintf("# range %s", dependency.Range)
		mappingSet(entry, newScalar("version"), versionNode)
		mappingSet(entry, newScalar("repository"), newScalar(repository))
		condition := "components." + dependency.Name + ".enabled"
		if dependency.Condition != "" {
			condition = dependency.Condition
		}
		mappingSet(entry, newScalar("condition"), newScalar(condition))
		dependencies.Content = append(dependencies.Content, entry)
	}
	dependenciesKey := newScalar("dependencies")
	dependenciesKey.HeadComment = "Exact pins resolved from the major-bounded ranges in curate.yaml (the tested BOM).\n" +
		"Chart.lock mirrors these pins; CI runs `helm dependency build` and fails on drift."
	mappingSet(chart, dependenciesKey, dependencies)

	document := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{chart}}
	document.HeadComment = "GENERATED by hack/curate.sh. Do not edit; change curate.yaml and run hack/curate.sh again."
	return document, nil
}

func checkMajor(dependency Dependency, version string) error {
	if !exactVersionRe.MatchString(version) {
		return fmt.Errorf("dependency %q resolved to %q, not an exact version", dependency.Name, version)
	}
	major, _, _ := strings.Cut(version, ".")
	if major != RangeMajor(dependency.Range) {
		return fmt.Errorf("dependency %q resolved to %s, outside range %s", dependency.Name, version, dependency.Range)
	}
	return nil
}
