package main

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

// GiantswarmExample derives examples/giantswarm.yaml: for every leaf the
// vanilla overlay changed, the value the fleet shipped before the overlay, then
// the per-installation inputs merged on top. The result turns the Giant Swarm
// defaults back on without a hand-maintained copy of them.
func GiantswarmExample(config *Config, beforeOverlay, overlay, inputs *yaml.Node) (*yaml.Node, error) {
	out := newMapping()
	if overlay != nil {
		if err := revertLeaves(out, beforeOverlay, rootMapping(overlay)); err != nil {
			return nil, err
		}
	}
	if inputs != nil {
		deepMerge(out, cloneNode(rootMapping(inputs)))
	}
	document := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{out}}
	document.HeadComment = fmt.Sprintf("GENERATED by hack/curate.sh from %s %s: the defaults overlay/vanilla.yaml\n"+
		"turns off, restored to the fleet values, plus the inputs of overlay/giantswarm.yaml.\n"+
		"Do not edit. What a Giant Swarm installation sets on top of the vanilla defaults.",
		config.Fleet.Chart, config.Fleet.Version)
	return document, nil
}

// revertLeaves walks the overlay; for each leaf (scalar, sequence or empty
// mapping) present in the fleet-derived values, the fleet node is copied into
// out at the same path. Leaves the overlay adds (no fleet counterpart) are
// skipped: they are umbrella inputs, not reverted defaults.
func revertLeaves(out, before, overlay *yaml.Node) error {
	for i := 0; i+1 < len(overlay.Content); i += 2 {
		key, value := overlay.Content[i], overlay.Content[i+1]
		_, fleetValue := mappingGet(before, key.Value)
		if fleetValue == nil {
			continue
		}
		if value.Kind == yaml.MappingNode && len(value.Content) > 0 {
			if fleetValue.Kind != yaml.MappingNode {
				return fmt.Errorf("overlay key %q is a mapping but the fleet value is not", key.Value)
			}
			child := newMapping()
			if err := revertLeaves(child, fleetValue, value); err != nil {
				return err
			}
			if len(child.Content) > 0 {
				mappingSet(out, newScalar(key.Value), child)
			}
			continue
		}
		mappingSet(out, newScalar(key.Value), cloneNode(fleetValue))
	}
	return nil
}
