package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestTransformShape(t *testing.T) {
	result, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	require.Len(t, result.Components, 5)
	document := result.Document

	values := decodeValues(t, document)
	require.Equal(t, []string{
		"global", "components", "ingress", "postgres", "gatewayApi", "muster", "kagent", "agent-platform-mcps", "agent-sandbox", "backstage",
	}, mappingKeys(rootMapping(document)), "keep, components, wiring, umbrella keys, then one block per dependency in dependency order")
	require.Empty(t, asMap(t, values["agent-sandbox"]), "a dependency without fleet values gets an empty block")
	require.Equal(t, false, asMap(t, asMap(t, values["backstage"])["ingress"])["enabled"], "the contract fills a dependency block")

	for _, dropped := range []string{"gitops", "mcps", "agentSandbox", "networkPolicy"} {
		require.NotContains(t, values, dropped)
	}

	componentsMap := asMap(t, values["components"])
	require.Equal(t, []string{"muster", "kagent", "agent-platform-mcps", "agent-sandbox", "backstage"},
		mappingKeys(mustGet(t, rootMapping(document), "components")))
	require.Equal(t, true, asMap(t, componentsMap["muster"])["enabled"], "no enabledFrom: the block's own enabled")
	require.Equal(t, false, asMap(t, componentsMap["kagent"])["enabled"], "enabledFrom kagent.enabled")
	require.Equal(t, true, asMap(t, componentsMap["agent-platform-mcps"])["enabled"], "enabledFrom mcps.enabled read before the toggle block is consumed")
	require.Equal(t, false, asMap(t, componentsMap["agent-sandbox"])["enabled"])
	require.Equal(t, false, asMap(t, componentsMap["backstage"])["enabled"], "extra dependency default")

	kagentWiring := asMap(t, componentsMap["kagent"])
	require.Contains(t, kagentWiring, "controllerRoute", "lifted wiring key")
	sandboxWiring := asMap(t, componentsMap["agent-sandbox"])
	require.Equal(t, true, asMap(t, sandboxWiring["podSecurity"])["enabled"])

	global := asMap(t, values["global"])
	require.Equal(t, []string{"registry", "networkPolicy", "domain"}, mappingKeys(mustGet(t, rootMapping(document), "global")),
		"kept keys, then the moved wiring block, then the overlay additions")
	netpol := asMap(t, global["networkPolicy"])
	require.Equal(t, false, netpol["enabled"], "overlay wins over the moved block")
	require.Equal(t, "kubernetes", netpol["flavor"])

	require.Equal(t, false, asMap(t, asMap(t, values["gatewayApi"])["gateway"])["create"], "umbrella key from the overlay")
	require.Equal(t, "kagent-pg", asMap(t, values["postgres"])["clusterName"], "wiring block kept where the fleet has it")

	muster := asMap(t, values["muster"])
	require.NotContains(t, muster, "enabled")
	require.Equal(t, "muster", muster["fullnameOverride"])

	kagentBlock := asMap(t, values["kagent"])
	require.Equal(t, []string{"kagent"}, keysOf(kagentBlock), "nested under valuesKey")
	inner := asMap(t, kagentBlock["kagent"])
	require.NotContains(t, inner, "enabled")
	require.NotContains(t, inner, "controllerRoute")
	require.Equal(t, "kagent-controller", asMap(t, inner["controller"])["image"])
	require.Empty(t, asMap(t, inner["controller"])["env"], "overlay replaces sequences")

	ingress := asMap(t, values["ingress"])
	require.Equal(t, true, ingress["fromConnectivity"], "wiring blocks come from the connectivity values")
}

func TestTransformPreservesCommentsAndSchemaAnnotations(t *testing.T) {
	result, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	out, err := encodeYAML(result.Document)
	require.NoError(t, err)
	text := string(out)
	require.Contains(t, text, "# route comment survives")
	require.Contains(t, text, "# netpol comment survives the move")
	require.Contains(t, text, "GENERATED by hack/curate.sh from agent-platform 2.13.0")
	require.Contains(t, text, "muster:  # @schema skipProperties: true", "the fleet annotation moves to the chart-name key")
	require.Contains(t, text, "kagent:  "+opaqueBlockAnnotation, "a block without a fleet annotation gets the opaque one")
	require.Contains(t, text, "backstage:  "+opaqueBlockAnnotation+"\n  ingress:", "a filled block is block-style, the annotation moves to the key")
	require.Contains(t, text, "labels: {}  # @schema type: object; additionalProperties: true", "an empty overlay mapping carries its annotation onto the fleet node")
}

func TestTransformBeforeOverlayIsUntouched(t *testing.T) {
	result, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	before := decodeValues(t, &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{result.BeforeOverlay}})
	netpol := asMap(t, asMap(t, before["global"])["networkPolicy"])
	require.Equal(t, true, netpol["enabled"], "the snapshot keeps the fleet default")
	require.Equal(t, false, asMap(t, asMap(t, before["gatewayApi"])["gateway"])["create"], "the snapshot includes the contract")
	require.NotContains(t, asMap(t, before["muster"]), "replicaCount")
}

func TestTransformDenyUnknownFleetKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, fixtureFleet+"brandNewFleetKey:\n  foo: bar\n")
	_, err := Transform(in)
	require.ErrorContains(t, err, `fleet key "brandNewFleetKey" has no entry`)
}

func TestTransformDenyUnknownConnectivityKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Connectivity = parseDocument(t, fixtureConnectivity+"brandNewWiringKey: {}\n")
	_, err := Transform(in)
	require.ErrorContains(t, err, `connectivity key "brandNewWiringKey" has no entry`)
}

func TestTransformDenyUnknownToggleSubKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "agentSandbox:\n  enabled: false\n", "agentSandbox:\n  enabled: false\n  surprise: 1\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, "keys.agentSandbox: sub-keys [surprise]")
}

func TestTransformNewFleetComponentFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "  agent-platform-connectivity:\n",
		"  shiny:\n    chart: shiny\n    repository: oci://example/charts\n  agent-platform-connectivity:\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `fleet component "shiny" (chart "shiny") is not a dependency`)
}

func TestTransformDependencyMissingFromFleetFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "  - name: muster\n    range: \"5.x\"\n",
		"  - name: muster\n    range: \"5.x\"\n  - name: ghost\n    range: \"1.x\"\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `dependency "ghost" is not a fleet component`)
}

func TestTransformLiftMissingKeyFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "lift: [controllerRoute]", "lift: [controllerRoute, uiRoute]", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `lift key "uiRoute" not found`)
}

func TestTransformUmbrellaKey(t *testing.T) {
	t.Run("must come from the overlay", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Contract = parseDocument(t, strings.Replace(fixtureContract, "gatewayApi:\n  gateway:\n    create: false\n", "", 1))
		_, err := Transform(in)
		require.ErrorContains(t, err, "keys.gatewayApi: action umbrella, but neither overlay defines it")
	})
	t.Run("fleet must not define it", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Fleet = parseDocument(t, fixtureFleet+"gatewayApi:\n  gateway: {}\n")
		_, err := Transform(in)
		require.ErrorContains(t, err, `fleet key "gatewayApi" is declared umbrella-only`)
	})
	t.Run("connectivity must not define it", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Connectivity = parseDocument(t, fixtureConnectivity+"gatewayApi:\n  gateway: {}\n")
		_, err := Transform(in)
		require.ErrorContains(t, err, `connectivity key "gatewayApi" is declared umbrella-only`)
	})
}

func TestTransformMoveToRejectsNonMapping(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "moveTo: global.networkPolicy", "moveTo: global.registry.networkPolicy", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `keys.networkPolicy: moveTo: "registry" is not a mapping`)
}

func TestConfigValidateMoveTo(t *testing.T) {
	var config Config
	require.NoError(t, yaml.Unmarshal([]byte(strings.Replace(fixtureConfig, "ingress: {action: wiring}", "ingress: {action: wiring, moveTo: flat}", 1)), &config))
	require.ErrorContains(t, config.Validate(), "keys.ingress: moveTo \"flat\" must be a dotted path")

	config = Config{}
	require.NoError(t, yaml.Unmarshal([]byte(strings.Replace(fixtureConfig, "global: {action: keep}", "global: {action: keep, moveTo: a.b}", 1)), &config))
	require.ErrorContains(t, config.Validate(), "keys.global: moveTo is only valid with action wiring")
}

func TestTransformOverlay(t *testing.T) {
	t.Run("unknown top-level key", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, fixtureOverlay+"notAnUmbrellaKey: 1\n")
		_, err := Transform(in)
		require.ErrorContains(t, err, `overlay key "notAnUmbrellaKey"`)
	})
	t.Run("unknown components entry", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, fixtureOverlay+"components:\n  nope:\n    enabled: true\n")
		_, err := Transform(in)
		require.ErrorContains(t, err, "overlay components.nope is not a dependency")
	})
	t.Run("applied last", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, fixtureOverlay+"components:\n  kagent:\n    enabled: true\ningress:\n  parentRefs:\n    - name: edge\n")
		result, err := Transform(in)
		require.NoError(t, err)
		values := decodeValues(t, result.Document)
		require.Equal(t, true, asMap(t, asMap(t, values["components"])["kagent"])["enabled"])
		require.Contains(t, asMap(t, asMap(t, values["components"])["kagent"]), "controllerRoute", "overlay merges, it does not replace")
		require.Equal(t, 1, asMap(t, values["muster"])["replicaCount"])
		require.Equal(t, "muster", asMap(t, values["muster"])["fullnameOverride"])
		require.Len(t, asMap(t, values["ingress"])["parentRefs"], 1, "sequences are replaced")
	})
}

func TestGiantswarmExample(t *testing.T) {
	in := fixtureInputs(t)
	result, err := Transform(in)
	require.NoError(t, err)

	example, err := GiantswarmExample(in.Config, result.BeforeOverlay, in.Overlay, parseDocument(t, fixtureGiantswarmInputs))
	require.NoError(t, err)
	values := decodeValues(t, example)

	global := asMap(t, values["global"])
	require.Equal(t, map[string]any{"enabled": true, "flavor": "cilium"}, asMap(t, global["networkPolicy"]), "the fleet default the overlay turned off")
	require.Equal(t, "example.gigantic.io", global["domain"], "inputs win over the reverted leaves")
	require.Equal(t, true, asMap(t, asMap(t, values["gatewayApi"])["gateway"])["create"], "an umbrella key has no fleet value; only the inputs set it")
	require.NotContains(t, values, "muster", "a leaf the fleet does not ship is not reverted")
	require.NotContains(t, values, "backstage", "the contract is not reverted")
	env := asMap(t, asMap(t, asMap(t, values["kagent"])["kagent"])["controller"])["env"]
	require.Len(t, env, 1, "a replaced sequence is restored whole")

	out, err := encodeYAML(example)
	require.NoError(t, err)
	require.Contains(t, string(out), "GENERATED by hack/curate.sh from agent-platform 2.13.0")
}

func keysOf(mapping map[string]any) []string {
	keys := make([]string, 0, len(mapping))
	for key := range mapping {
		keys = append(keys, key)
	}
	return keys
}
