package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestTransformShape(t *testing.T) {
	result, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	document, components := result.Document, result.Components
	require.Len(t, components, 5)

	values := decodeValues(t, document)
	require.Equal(t, []string{
		"global", "components", "ingress", "muster", "kagent", "agent-platform-mcps", "agent-sandbox", "backstage",
	}, mappingKeys(rootMapping(document)), "keep, components, wiring, then one block per dependency in dependency order")
	require.Empty(t, asMap(t, values["agent-sandbox"]), "a dependency without fleet values gets an empty block")
	require.Empty(t, asMap(t, values["backstage"]))

	for _, dropped := range []string{"gitops", "agentSandbox"} {
		require.NotContains(t, values, dropped)
	}

	componentsMap := asMap(t, values["components"])
	require.Equal(t, []string{"muster", "kagent", "agent-platform-mcps", "agent-sandbox", "backstage"},
		mappingKeys(mustGet(t, rootMapping(document), "components")))
	require.Equal(t, true, asMap(t, componentsMap["muster"])["enabled"], "a fleet entry without `enabled` is on")
	require.Equal(t, false, asMap(t, componentsMap["kagent"])["enabled"], "the fleet components.kagent.enabled default")
	require.Equal(t, true, asMap(t, componentsMap["agent-platform-mcps"])["enabled"])
	require.Equal(t, false, asMap(t, componentsMap["agent-sandbox"])["enabled"], "a component with no values block still takes its fleet default")
	require.Equal(t, false, asMap(t, componentsMap["backstage"])["enabled"], "extra dependency default")

	kagentWiring := asMap(t, componentsMap["kagent"])
	require.Contains(t, kagentWiring, "controllerRoute", "lifted wiring key")
	sandboxWiring := asMap(t, componentsMap["agent-sandbox"])
	require.Equal(t, true, asMap(t, sandboxWiring["podSecurity"])["enabled"])

	muster := asMap(t, values["muster"])
	require.Equal(t, true, muster["enabled"], "keepEnabled forwards the key the muster chart owns")
	require.Equal(t, "muster", muster["fullnameOverride"])

	kagentBlock := asMap(t, values["kagent"])
	require.Equal(t, []string{"kagent"}, keysOf(kagentBlock), "nested under valuesKey")
	inner := asMap(t, kagentBlock["kagent"])
	require.NotContains(t, inner, "enabled")
	require.NotContains(t, inner, "controllerRoute")
	require.Equal(t, "kagent-controller", asMap(t, inner["controller"])["image"])

	ingress := asMap(t, values["ingress"])
	require.Equal(t, true, ingress["fromConnectivity"], "wiring blocks come from the connectivity values")
}

func TestTransformPreservesCommentsAndSchemaAnnotations(t *testing.T) {
	result, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	out, err := encodeYAML(result.Document)
	require.NoError(t, err)
	text := string(out)
	require.Contains(t, text, "# route comment survives")
	require.Contains(t, text, "GENERATED by hack/curate.sh from agent-platform 3.0.0")
	require.Contains(t, text, "muster:  # @schema skipProperties: true", "the fleet annotation moves to the chart-name key")
	require.Contains(t, text, "kagent:  "+opaqueBlockAnnotation, "a block without a fleet annotation gets the opaque one")
	require.Contains(t, text, "backstage: {}  "+opaqueBlockAnnotation)
}

func TestTransformDenyUnknownFleetKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, fixtureFleet+"brandNewFleetKey:\n  foo: bar\n")
	_, err := Transform(in)
	require.ErrorContains(t, err, `fleet key "brandNewFleetKey" has no entry`)
}

func TestTransformDenyUnknownConnectivityKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Connectivity = parseDocument(t, fixtureConnectivity+"gatewayApi: {}\n")
	_, err := Transform(in)
	require.ErrorContains(t, err, `connectivity key "gatewayApi" has no entry`)
}

func TestTransformDenyUnknownLiftSubKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "agentSandbox:\n", "agentSandbox:\n  surprise: 1\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, "keys.agentSandbox: sub-keys [surprise]")
}

// A toggle that returns to a component block would be read by nothing: the
// blocks accept unknown keys, so the component would silently take the
// components.<chart>.enabled default instead.
func TestTransformRejectsLegacyToggle(t *testing.T) {
	t.Run("component block", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "kagent:\n  # route comment survives\n", "kagent:\n  enabled: true\n  # route comment survives\n", 1))
		_, err := Transform(in)
		require.ErrorContains(t, err, "fleet block \"kagent\" carries a top-level `enabled`, which components.kagent.enabled replaced")
	})
	t.Run("lift block", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "agentSandbox:\n", "agentSandbox:\n  enabled: false\n", 1))
		_, err := Transform(in)
		require.ErrorContains(t, err, "components.agent-sandbox.enabled replaced")
	})
	t.Run("keepEnabled allows it", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Config = parseConfig(t, strings.Replace(fixtureConfig, "  muster:\n    action: component\n    keepEnabled: true\n    allowShadow: true\n", "  muster: {action: component, allowShadow: true}\n", 1))
		_, err := Transform(in)
		require.ErrorContains(t, err, `fleet block "muster" carries a top-level `+"`enabled`")
	})
}

func TestTransformRejectsOmitKeys(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "    valuesFrom: kagent\n", "    valuesFrom: kagent\n    omitKeys: [controllerRoute]\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `fleet component "kagent" declares omitKeys`)
}

func TestTransformNewFleetComponentFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "  agent-platform-connectivity:\n",
		"  shiny:\n    chart: shiny\n    repository: oci://example/charts\n  agent-platform-connectivity:\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `fleet component "shiny" (chart "shiny") is not a dependency`)
}

func TestTransformDependencyMissingFromFleetFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "  - name: muster\n    range: \"5.x\"\n",
		"  - name: muster\n    range: \"5.x\"\n  - name: ghost\n    range: \"1.x\"\n", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `dependency "ghost" is not a fleet component`)
}

func TestTransformLiftMissingKeyFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "lift: [controllerRoute]", "lift: [controllerRoute, uiRoute]", 1))
	_, err := Transform(in)
	require.ErrorContains(t, err, `lift key "uiRoute" not found`)
}

func TestTransformOverlay(t *testing.T) {
	t.Run("unknown top-level key", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, "policyEngine: none\n")
		_, err := Transform(in)
		require.ErrorContains(t, err, `overlay key "policyEngine"`)
	})
	t.Run("unknown components entry", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, "components:\n  nope:\n    enabled: true\n")
		_, err := Transform(in)
		require.ErrorContains(t, err, "overlay components.nope is not a dependency")
	})
	t.Run("applied last", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, "components:\n  kagent:\n    enabled: true\nmuster:\n  replicaCount: 2\ningress:\n  parentRefs:\n    - name: edge\n")
		result, err := Transform(in)
		require.NoError(t, err)
		values := decodeValues(t, result.Document)
		require.Equal(t, true, asMap(t, asMap(t, values["components"])["kagent"])["enabled"])
		require.Contains(t, asMap(t, asMap(t, values["components"])["kagent"]), "controllerRoute", "overlay merges, it does not replace")
		require.Equal(t, 2, asMap(t, values["muster"])["replicaCount"])
		require.Equal(t, "muster", asMap(t, values["muster"])["fullnameOverride"])
		require.Len(t, asMap(t, values["ingress"])["parentRefs"], 1, "sequences are replaced")
	})
}

// A key that appears in the source chart its rule does not read is discarded;
// without an explicit allowShadow declaration that discard must fail the run,
// so the two copies cannot drift apart unnoticed.
func TestTransformRejectsUndeclaredShadow(t *testing.T) {
	t.Run("wiring key in the fleet values", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Config = parseConfig(t, strings.Replace(fixtureConfig,
			"  ingress: {action: wiring, allowShadow: true}\n", "  ingress: {action: wiring}\n", 1))
		_, err := Transform(in)
		require.ErrorContains(t, err, `fleet values carry "ingress"`)
	})
	t.Run("fleet-owned key in the connectivity values", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Config = parseConfig(t, strings.Replace(fixtureConfig,
			"  global: {action: keep, allowShadow: true}\n", "  global: {action: keep}\n", 1))
		_, err := Transform(in)
		require.ErrorContains(t, err, `connectivity values carry "global"`)
	})
}

// The overlay merges after the fleet-side toggle guard ran, so it must not
// smuggle back a component-level `enabled` of its own.
func TestTransformOverlayRejectsBlockToggle(t *testing.T) {
	in := fixtureInputs(t)
	in.Overlay = parseDocument(t, "kagent:\n  enabled: false\n")
	_, err := Transform(in)
	require.ErrorContains(t, err, "overlay block \"kagent\" carries a top-level `enabled`")

	in = fixtureInputs(t)
	in.Overlay = parseDocument(t, "muster:\n  enabled: false\n")
	_, err = Transform(in)
	require.NoError(t, err, "the muster chart owns its enabled key (keepEnabled)")
}

func TestTransformAnnotations(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, fixtureConfig+"annotations:\n  ingress.parentRefs: \"item: object\"\n  muster.fullnameOverride: \"enum:[muster]\"\n")
	result, err := Transform(in)
	require.NoError(t, err)
	out, err := encodeYAML(result.Document)
	require.NoError(t, err)
	require.Contains(t, string(out), "parentRefs: []  # @schema item: object", "flow value carries the comment")
	require.Contains(t, string(out), "fullnameOverride: muster  # @schema enum:[muster]", "scalar value carries the comment")

	in = fixtureInputs(t)
	in.Config = parseConfig(t, fixtureConfig+"annotations:\n  ingress.gone: \"item: object\"\n")
	_, err = Transform(in)
	require.ErrorContains(t, err, "annotations.ingress.gone")
}

func keysOf(mapping map[string]any) []string {
	keys := make([]string, 0, len(mapping))
	for key := range mapping {
		keys = append(keys, key)
	}
	return keys
}
