package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestTransformShape(t *testing.T) {
	document, components, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	require.Len(t, components, 5)

	values := decodeValues(t, document)
	require.Equal(t, []string{
		"global", "components", "ingress", "muster", "kagent", "agent-platform-mcps", "agent-sandbox", "backstage",
	}, mappingKeys(rootMapping(document)), "keep, components, wiring, then one block per dependency in dependency order")
	require.Empty(t, asMap(t, values["agent-sandbox"]), "a dependency without fleet values gets an empty block")
	require.Empty(t, asMap(t, values["backstage"]))

	for _, dropped := range []string{"gitops", "mcps", "agentSandbox"} {
		require.NotContains(t, values, dropped)
	}

	componentsMap := asMap(t, values["components"])
	require.Equal(t, []string{"muster", "kagent", "agent-platform-mcps", "agent-sandbox", "backstage"},
		mappingKeys(mustGet(t, rootMapping(document), "components")))
	require.Equal(t, true, asMap(t, componentsMap["muster"])["enabled"], "no enabledFrom: the block's own enabled")
	require.Equal(t, false, asMap(t, componentsMap["kagent"])["enabled"], "enabledFrom kagent.enabled")
	require.Equal(t, true, asMap(t, componentsMap["agent-platform-mcps"])["enabled"], "enabledFrom mcps.enabled read before the toggle block is consumed")
	require.Equal(t, false, asMap(t, componentsMap["agent-sandbox"])["enabled"])
	require.Equal(t, false, asMap(t, componentsMap["backstage"])["enabled"], "extra dependency default")

	kagentWiring := asMap(t, componentsMap["kagent"])
	require.Contains(t, kagentWiring, "controllerRoute", "lifted wiring key")
	sandboxWiring := asMap(t, componentsMap["agent-sandbox"])
	require.Equal(t, true, asMap(t, sandboxWiring["podSecurity"])["enabled"])

	muster := asMap(t, values["muster"])
	require.NotContains(t, muster, "enabled")
	require.Equal(t, "muster", muster["fullnameOverride"])

	kagentBlock := asMap(t, values["kagent"])
	require.Equal(t, []string{"kagent"}, keysOf(kagentBlock), "nested under valuesKey")
	inner := asMap(t, kagentBlock["kagent"])
	require.NotContains(t, inner, "enabled")
	require.NotContains(t, inner, "controllerRoute")
	require.Equal(t, "kagent-controller", asMap(t, inner["controller"])["image"])

	ingress := asMap(t, values["ingress"])
	require.Equal(t, true, ingress["fromConnectivity"], "wiring blocks come from the connectivity values")
}

func TestTransformPreservesCommentsAndSchemaAnnotations(t *testing.T) {
	document, _, err := Transform(fixtureInputs(t))
	require.NoError(t, err)
	out, err := encodeYAML(document)
	require.NoError(t, err)
	text := string(out)
	require.Contains(t, text, "# route comment survives")
	require.Contains(t, text, "GENERATED by hack/curate.sh from agent-platform 2.13.0")
	require.Contains(t, text, "muster:  # @schema skipProperties: true", "the fleet annotation moves to the chart-name key")
	require.Contains(t, text, "kagent:  "+opaqueBlockAnnotation, "a block without a fleet annotation gets the opaque one")
	require.Contains(t, text, "backstage: {}  "+opaqueBlockAnnotation)
}

func TestTransformDenyUnknownFleetKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, fixtureFleet+"brandNewFleetKey:\n  foo: bar\n")
	_, _, err := Transform(in)
	require.ErrorContains(t, err, `fleet key "brandNewFleetKey" has no entry`)
}

func TestTransformDenyUnknownConnectivityKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Connectivity = parseDocument(t, fixtureConnectivity+"gatewayApi: {}\n")
	_, _, err := Transform(in)
	require.ErrorContains(t, err, `connectivity key "gatewayApi" has no entry`)
}

func TestTransformDenyUnknownToggleSubKey(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "agentSandbox:\n  enabled: false\n", "agentSandbox:\n  enabled: false\n  surprise: 1\n", 1))
	_, _, err := Transform(in)
	require.ErrorContains(t, err, "keys.agentSandbox: sub-keys [surprise]")
}

func TestTransformNewFleetComponentFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Fleet = parseDocument(t, strings.Replace(fixtureFleet, "  agent-platform-connectivity:\n",
		"  shiny:\n    chart: shiny\n    repository: oci://example/charts\n  agent-platform-connectivity:\n", 1))
	_, _, err := Transform(in)
	require.ErrorContains(t, err, `fleet component "shiny" (chart "shiny") is not a dependency`)
}

func TestTransformDependencyMissingFromFleetFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "  - name: muster\n    range: \"5.x\"\n",
		"  - name: muster\n    range: \"5.x\"\n  - name: ghost\n    range: \"1.x\"\n", 1))
	_, _, err := Transform(in)
	require.ErrorContains(t, err, `dependency "ghost" is not a fleet component`)
}

func TestTransformLiftMissingKeyFails(t *testing.T) {
	in := fixtureInputs(t)
	in.Config = parseConfig(t, strings.Replace(fixtureConfig, "lift: [controllerRoute]", "lift: [controllerRoute, uiRoute]", 1))
	_, _, err := Transform(in)
	require.ErrorContains(t, err, `lift key "uiRoute" not found`)
}

func TestTransformOverlay(t *testing.T) {
	t.Run("unknown top-level key", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, "policyEngine: none\n")
		_, _, err := Transform(in)
		require.ErrorContains(t, err, `overlay key "policyEngine"`)
	})
	t.Run("unknown components entry", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, "components:\n  nope:\n    enabled: true\n")
		_, _, err := Transform(in)
		require.ErrorContains(t, err, "overlay components.nope is not a dependency")
	})
	t.Run("applied last", func(t *testing.T) {
		in := fixtureInputs(t)
		in.Overlay = parseDocument(t, "components:\n  kagent:\n    enabled: true\nmuster:\n  replicaCount: 2\ningress:\n  parentRefs:\n    - name: edge\n")
		document, _, err := Transform(in)
		require.NoError(t, err)
		values := decodeValues(t, document)
		require.Equal(t, true, asMap(t, asMap(t, values["components"])["kagent"])["enabled"])
		require.Contains(t, asMap(t, asMap(t, values["components"])["kagent"]), "controllerRoute", "overlay merges, it does not replace")
		require.Equal(t, 2, asMap(t, values["muster"])["replicaCount"])
		require.Equal(t, "muster", asMap(t, values["muster"])["fullnameOverride"])
		require.Len(t, asMap(t, values["ingress"])["parentRefs"], 1, "sequences are replaced")
	})
}

func keysOf(mapping map[string]any) []string {
	keys := make([]string, 0, len(mapping))
	for key := range mapping {
		keys = append(keys, key)
	}
	return keys
}
